apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

nameSuffix: -dev

## patch the ApplicationSet to include specifics for this environment
patches:
  - target:
      kind: ApplicationSet
    path: myApp-releasemanager.yml