apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-releasemanager
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - environment: dev
        appName: bookinfo
        appNamespace: bookinfo-dev
        repoURL: https://github.com/bry-tam/app-sample-rollout.git
        path: bookinfo/environments/dev
        revision: bookinfo-v1

      - environment: dev
        appName: bookinfo-details
        appNamespace: bookinfo-dev
        repoURL: https://github.com/bry-tam/app-sample-rollout.git
        path: details/environments/dev
        revision: bookinfo-v1

      - environment: dev
        appName: bookinfo-productpage
        appNamespace: bookinfo-dev
        repoURL: https://github.com/bry-tam/app-sample-rollout.git
        path: productpage/environments/dev
        revision: bookinfo-v1

      - environment: dev
        appName: bookinfo-ratings
        appNamespace: bookinfo-dev
        repoURL: https://github.com/bry-tam/app-sample-rollout.git
        path: ratings/environments/dev
        revision: bookinfo-v1

      - environment: dev
        appName: bookinfo-reviews
        appNamespace: bookinfo-dev
        repoURL: https://github.com/bry-tam/app-sample-rollout.git
        path: reviews/environments/dev
        revision: bookinfo-v1